export const DEFAULT_PORT = 8080;
export const ROOM_ID_LENGTH = 6;
export const ROOM_ID_CHARSET = "0123456789";

export const MAX_PASSWORD_ATTEMPTS = 5;
export const IP_BLOCK_DURATION_MS = 10 * 60 * 1000;

export const ROOM_CLEANUP_INTERVAL_MS = 60 * 1000;

export const ERROR_CODES = {
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  ROOM_ALREADY_EXISTS: "ROOM_ALREADY_EXISTS",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  TOO_MANY_ATTEMPTS: "TOO_MANY_ATTEMPTS",
  HOST_NOT_CONNECTED: "HOST_NOT_CONNECTED",
  VIEWER_NOT_FOUND: "VIEWER_NOT_FOUND",
  INVALID_MESSAGE: "INVALID_MESSAGE",
  UNAUTHORIZED: "UNAUTHORIZED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
